# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meterusage.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10meterusage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x13\n\x11MeterUsageRequest\"3\n\x12MeterUsageResponse\x12\x1d\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0f.MeterUsageData\"N\n\x0eMeterUsageData\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nmeterusage\x18\x02 \x01(\x02\x32H\n\nMeterUsage\x12:\n\rGetMeterUsage\x12\x12.MeterUsageRequest\x1a\x13.MeterUsageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meterusage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_METERUSAGEREQUEST']._serialized_start=53
  _globals['_METERUSAGEREQUEST']._serialized_end=72
  _globals['_METERUSAGERESPONSE']._serialized_start=74
  _globals['_METERUSAGERESPONSE']._serialized_end=125
  _globals['_METERUSAGEDATA']._serialized_start=127
  _globals['_METERUSAGEDATA']._serialized_end=205
  _globals['_METERUSAGE']._serialized_start=207
  _globals['_METERUSAGE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
